import { useMemo } from 'react';
import { Link } from 'react-router-dom';
import { simulateTopology } from '../simulations/engine';
import { defaultParams } from '../state/LabContext';
import { ClassificationTree } from '../components/ClassificationTree';
import { ConverterGrid } from '../components/ConverterSelector';

function Scope() {
  const r = useMemo(() => simulateTopology('fc-3ph', { ...defaultParams('fc-3ph'), alpha: 45, L_mH: 50, tSim_ms: 40 }), []);
  const s = r.series;
  const W = 640, H = 240;
  const maxV = Math.max(...Array.from(s.vo).map(Math.abs), 1) * 1.1;
  const pt = (arr: Float64Array) => Array.from(arr).map((v, i) => `${(i / (s.n - 1)) * W},${H / 2 - (v / maxV) * (H / 2 - 8)}`).join(' ');
  return (
    <svg viewBox={`0 0 ${W} ${H}`} className="w-full" role="img" aria-label="Live three-phase waveform generated by the simulation engine">
      {Array.from({ length: 9 }).map((_, i) => <line key={i} x1={(i * W) / 8} x2={(i * W) / 8} y1={0} y2={H} stroke="var(--border)" />)}
      {Array.from({ length: 5 }).map((_, i) => <line key={i} y1={(i * H) / 4} y2={(i * H) / 4} x1={0} x2={W} stroke="var(--border)" />)}
      {[0, 1, 2].map((k) => <polyline key={k} points={pt(s.vin[k])} fill="none" stroke={['#f87171', '#facc15', '#60a5fa'][k]} strokeWidth={1.2} opacity={0.55} />)}
      <polyline points={pt(s.vo)} fill="none" stroke="var(--accent)" strokeWidth={2.4} />
    </svg>
  );
}

const FEATURES = [
  ['Real numerical engine', 'Every waveform comes from switching logic and an exact L·di/dt + Ri = vo integrator — no canned images.'],
  ['10 rectifier topologies', 'Diode and SCR circuits, single- and three-phase, with R or R-L loads and optional freewheeling diode.'],
  ['Live schematics', 'Conducting devices, gate pulses and current direction light up in sync with the waveforms.'],
  ['Theory vs simulation', 'Closed-form results are compared with the simulated steady state, with percentage error.'],
  ['Honest validation', 'Bad R, L or α values are flagged, and continuous-conduction formulas are never silently misapplied.'],
  ['Compare side by side', 'Put 2–4 converters under the same load and see how Vdc, ripple, PF and THD differ.'],
];

export default function Home() {
  return (
    <div className="mx-auto w-full max-w-[1280px] px-4 py-8 grid gap-12">
      <section className="grid gap-8 lg:grid-cols-2 items-center">
        <div>
          <div className="eyebrow">Interactive power electronics lab</div>
          <h1 className="m-0 mt-2" style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(30px,5vw,48px)', lineHeight: 1.08, fontWeight: 700 }}>
            AC → DC Rectifier <span style={{ color: 'var(--accent)' }}>Virtual Laboratory</span>
          </h1>
          <p className="mt-4 text-[15px] max-w-xl" style={{ color: 'var(--muted)' }}>
            Pick a converter, set the source, load and firing angle, and watch the circuit conduct while the waveforms, ripple, power factor and harmonics are computed from the physics.
          </p>
          <div className="flex flex-wrap gap-3 mt-6">
            <Link to="/simulator" className="btn btn-primary">Open simulator</Link>
            <Link to="/converters" className="btn">Browse converters</Link>
            <Link to="/compare" className="btn">Compare rectifiers</Link>
          </div>
        </div>
        <div className="panel">
          <div className="panel-head"><div><div className="eyebrow">Generated live by the engine</div><div className="panel-title">3φ fully controlled bridge · α = 45° · RL load</div></div></div>
          <div className="panel-body" style={{ background: 'var(--bg-soft)' }}><Scope /></div>
        </div>
      </section>

      <section>
        <h2 className="panel-title mb-3" style={{ fontSize: 20 }}>Classification of rectifiers</h2>
        <ClassificationTree />
      </section>

      <section>
        <h2 className="panel-title mb-4" style={{ fontSize: 20 }}>Choose a converter</h2>
        <ConverterGrid />
      </section>

      <section>
        <h2 className="panel-title mb-4" style={{ fontSize: 20 }}>What you get</h2>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map(([t, d]) => (
            <div key={t} className="panel"><div className="panel-body"><div className="panel-title">{t}</div><p className="m-0 mt-1.5 text-[13.5px]" style={{ color: 'var(--muted)' }}>{d}</p></div></div>
          ))}
        </div>
      </section>
    </div>
  );
}
